netbox_cmdb/netbox_cmdb/urls.py
"""URLs."""

from django.urls import path
from netbox.views.generic import ObjectChangeLogView, ObjectJournalView

from netbox_cmdb.models.bgp import ASN, BGPSession, DeviceBGPSession, BGPPeerGroup
from netbox_cmdb.models.route_policy import RoutePolicy
from netbox_cmdb.models.snmp import SNMP, SNMPCommunity
from netbox_cmdb.models.syslog import Syslog, SyslogServer
from netbox_cmdb.models.tacacs import Tacacs, TacacsServer
from netbox_cmdb.views import (
    ASNDeleteView,
    ASNEditView,
    ASNListView,
    ASNView,
    BGPPeerGroupDeleteView,
    BGPPeerGroupEditView,
    BGPPeerGroupListView,
    BGPPeerGroupView,
    BGPSessionBulkDeleteView,
    BGPSessionDeleteView,
    BGPSessionEditView,
    BGPSessionListView,
    BGPSessionView,
    DeviceBGPSessionEditView,
    DeviceBGPSessionListView,
    DeviceBGPSessionView,
    DeviceDecommissioningView,
    DeviceBGPSessionDeleteView,
    RoutePolicyDeleteView,
    RoutePolicyEditView,
    RoutePolicyListView,
    RoutePolicyView,
    SiteDecommissioningView,
    SNMPCommunityDeleteView,
    SNMPCommunityEditView,
    SNMPCommunityListView,
    SNMPDeleteView,
    SNMPEditView,
    SNMPListView,
    SyslogListView,
    SyslogEditView,
    SyslogDeleteView,
    SyslogServerListView,
    SyslogServerEditView,
    SyslogServerDeleteView,
    TacacsListView,
    TacacsEditView,
    TacacsDeleteView,
    TacacsServerListView,
    TacacsServerEditView,
    TacacsServerDeleteView,
)

urlpatterns = [
    path(
        "decommissioning/device/<int:pk>/delete",
        DeviceDecommissioningView.as_view(),
        name="device_decommissioning_delete",
    ),
    path(
        "decommissioning/site/<int:pk>/delete",
        SiteDecommissioningView.as_view(),
        name="site_decommissioning_delete",
    ),
    # ASN
    path("asn/", ASNListView.as_view(), name="asn_list"),
    path("asn/add/", ASNEditView.as_view(), name="asn_add"),
    path("asn/<int:pk>/", ASNView.as_view(), name="asn"),
    path("asn/<int:pk>/edit/", ASNEditView.as_view(), name="asn_edit"),
    path("asn/<int:pk>/delete/", ASNDeleteView.as_view(), name="asn_delete"),
    path(
        "asn/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="asn_changelog",
        kwargs={"model": ASN},
    ),
    path(
        "asn/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="asn_journal",
        kwargs={"model": ASN},
    ),
    # BGP session
    path("bgp-session/", BGPSessionListView.as_view(), name="bgpsession_list"),
    path("bgp-session/add/", BGPSessionEditView.as_view(), name="bgpsession_add"),
    path("bgp-session/<int:pk>/", BGPSessionView.as_view(), name="bgpsession"),
    path(
        "bgp-session/<int:pk>/edit/",
        BGPSessionEditView.as_view(),
        name="bgpsession_edit",
    ),
    path(
        "bgp-session/<int:pk>/delete/",
        BGPSessionDeleteView.as_view(),
        name="bgpsession_delete",
    ),
    path("bgp-session/delete/", BGPSessionBulkDeleteView.as_view(), name="bgpsession_bulk_delete"),
    path(
        "bgp-session/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="bgpsession_changelog",
        kwargs={"model": BGPSession},
    ),
    path(
        "bgp-session/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="bgpsession_journal",
        kwargs={"model": BGPSession},
    ),
    # Device BGP session
    path("device-bgp-session/", DeviceBGPSessionListView.as_view(), name="devicebgpsession_list"),
    path("device-bgp-session/add", DeviceBGPSessionEditView.as_view(), name="devicebgpsession_add"),
    path("device-bgp-session/<int:pk>/", DeviceBGPSessionView.as_view(), name="devicebgpsession"),
    path(
        "device-bgp-session/<int:pk>/edit",
        DeviceBGPSessionEditView.as_view(),
        name="devicebgpsession_edit",
    ),
    path(
        "device-bgp-session/<int:pk>/delete",
        DeviceBGPSessionDeleteView.as_view(),
        name="devicebgpsession_delete",
    ),
    path(
        "device-bgp-session/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="devicebgpsession_changelog",
        kwargs={"model": DeviceBGPSession},
    ),
    # Peer Group
    path("peer-group/", BGPPeerGroupListView.as_view(), name="bgppeergroup_list"),
    path("peer-group/add/", BGPPeerGroupEditView.as_view(), name="bgppeergroup_add"),
    path("peer-group/<int:pk>/", BGPPeerGroupView.as_view(), name="bgppeergroup"),
    path(
        "peer-group/<int:pk>/edit/",
        BGPPeerGroupEditView.as_view(),
        name="bgppeergroup_edit",
    ),
    path(
        "peer-group/<int:pk>/delete/",
        BGPPeerGroupDeleteView.as_view(),
        name="bgppeergroup_delete",
    ),
    path(
        "peer-group/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="bgppeergroup_changelog",
        kwargs={"model": BGPPeerGroup},
    ),
    path(
        "peer-group/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="bgppeergroup_journal",
        kwargs={"model": BGPPeerGroup},
    ),
    # Route Policy
    path("route-policy/", RoutePolicyListView.as_view(), name="routepolicy_list"),
    path("route-policy/add/", RoutePolicyEditView.as_view(), name="routepolicy_add"),
    path("route-policy/<int:pk>/", RoutePolicyView.as_view(), name="routepolicy"),
    path(
        "route-policy/<int:pk>/edit/",
        RoutePolicyEditView.as_view(),
        name="routepolicy_edit",
    ),
    path(
        "route-policy/<int:pk>/delete/",
        RoutePolicyDeleteView.as_view(),
        name="routepolicy_delete",
    ),
    path(
        "route-policy/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="routepolicy_changelog",
        kwargs={"model": RoutePolicy},
    ),
    path(
        "route-policy/<int:pk>/journal/",
        ObjectJournalView.as_view(),
        name="routepolicy_journal",
        kwargs={"model": RoutePolicy},
    ),
    # SNMP
    path("snmp/", SNMPListView.as_view(), name="snmp_list"),
    path("snmp/add/", SNMPEditView.as_view(), name="snmp_add"),
    path(
        "snmp/<int:pk>/edit/",
        SNMPEditView.as_view(),
        name="snmp_edit",
    ),
    path(
        "snmp/<int:pk>/delete/",
        SNMPDeleteView.as_view(),
        name="snmp_delete",
    ),
    path(
        "snmp/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="snmp_changelog",
        kwargs={"model": SNMP},
    ),
    # SNMP Community
    path("snmp-community/", SNMPCommunityListView.as_view(), name="snmpcommunity_list"),
    path("snmp-community/add/", SNMPCommunityEditView.as_view(), name="snmpcommunity_add"),
    path(
        "snmp-community/<int:pk>/edit/",
        SNMPCommunityEditView.as_view(),
        name="snmpcommunity_edit",
    ),
    path(
        "snmp-community/<int:pk>/delete/",
        SNMPCommunityDeleteView.as_view(),
        name="snmpcommunity_delete",
    ),
    path(
        "snmp-community/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="snmpcommunity_changelog",
        kwargs={"model": SNMPCommunity},
    ),
    # SYSLOG
    path("syslog/", SyslogListView.as_view(), name="syslog_list"),
    path("syslog/add/", SyslogEditView.as_view(), name="syslog_add"),
    path(
        "syslog/<int:pk>/edit/",
        SyslogEditView.as_view(),
        name="syslog_edit",
    ),
    path(
        "syslog/<int:pk>/delete/",
        SyslogDeleteView.as_view(),
        name="syslog_delete",
    ),
    path(
        "syslog/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="syslog_changelog",
        kwargs={"model": Syslog},
    ),
    # SYSLOG SERVERS
    path("syslog-server/", SyslogServerListView.as_view(), name="syslogserver_list"),
    path("syslog-server/add/", SyslogServerEditView.as_view(), name="syslogserver_add"),
    path(
        "syslog-server/<int:pk>/edit/",
        SyslogServerEditView.as_view(),
        name="syslogserver_edit",
    ),
    path(
        "syslog-server/<int:pk>/delete/",
        SyslogServerDeleteView.as_view(),
        name="syslogserver_delete",
    ),
    path(
        "syslog-server/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="syslogserver_changelog",
        kwargs={"model": SyslogServer},
    ),
    # TACACS
    path("tacacs/", TacacsListView.as_view(), name="tacacs_list"),
    path("tacacs/add/", TacacsEditView.as_view(), name="tacacs_add"),
    path(
        "tacacs/<int:pk>/edit/",
        TacacsEditView.as_view(),
        name="tacacs_edit",
    ),
    path(
        "tacacs/<int:pk>/delete/",
        TacacsDeleteView.as_view(),
        name="tacacs_delete",
    ),
    path(
        "tacacs/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="tacacs_changelog",
        kwargs={"model": Tacacs},
    ),
    # TACACS SERVERS
    path("tacacs-server/", TacacsServerListView.as_view(), name="tacacsserver_list"),
    path("tacacs-server/add/", TacacsServerEditView.as_view(), name="tacacsserver_add"),
    path(
        "tacacs-server/<int:pk>/edit/",
        TacacsServerEditView.as_view(),
        name="tacacsserver_edit",
    ),
    path(
        "tacacs-server/<int:pk>/delete/",
        TacacsServerDeleteView.as_view(),
        name="tacacsserver_delete",
    ),
    path(
        "tacacs-server/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="tacacsserver_changelog",
        kwargs={"model": TacacsServer},
    ),
]

netbox_cmdb/netbox_cmdb/models/interface.py
from django.core.exceptions import ValidationError
from django.db import models
from netbox.models import ChangeLoggedModel

from netbox_cmdb import protect
from netbox_cmdb.choices import AssetMonitoringStateChoices, AssetStateChoices

FEC_CHOICES = [
    (None, "None"),
    ("rs", "Reed Solomon"),
    ("fc", "FireCode"),
]

LOGICAL_INTERFACE_TYPE_CHOICES = [
    ("l1", "L1"),
    ("l2", "L2"),
    ("l3", "L3"),
]
LOGICAL_INTERFACE_MODE_CHOICES = [
    (None, "None"),
    ("access", "Access"),
    ("tagged", "Tagged"),
]


@protect.from_device_name_change("device")
class DeviceInterface(ChangeLoggedModel):
    """A device interface configuration."""

    name = models.CharField(max_length=100)
    enabled = models.BooleanField(default=True)
    state = models.CharField(
        max_length=50,
        choices=AssetStateChoices,
        default=AssetStateChoices.STATE_STAGING,
        help_text="State of this DeviceInterface",
    )
    monitoring_state = models.CharField(
        max_length=50,
        choices=AssetMonitoringStateChoices,
        default=AssetMonitoringStateChoices.DISABLED,
        help_text="Monitoring state of this DeviceInterface",
    )
    device = models.ForeignKey(
        to="dcim.Device",
        on_delete=models.CASCADE,
        related_name="%(class)sdevice",
        null=False,
        blank=False,
    )
    autonegotiation = models.BooleanField(default=True)
    speed = models.PositiveIntegerField(
        blank=True,
        null=True,
        help_text="Interface speed in kb/s",
    )
    fec = models.CharField(
        choices=FEC_CHOICES,
        max_length=5,
        blank=True,
        null=True,
    )
    description = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.device.name}--{self.name}"

    class Meta:
        unique_together = ("device", "name")


@protect.from_ip_address_change("ipv4_address", "ipv6_address")
class LogicalInterface(ChangeLoggedModel):
    """A logical interface configuration."""

    index = models.PositiveSmallIntegerField()
    enabled = models.BooleanField(default=True)
    state = models.CharField(
        max_length=50,
        choices=AssetStateChoices,
        default=AssetStateChoices.STATE_STAGING,
        help_text="State of this LogicalInterface",
    )
    monitoring_state = models.CharField(
        max_length=50,
        choices=AssetMonitoringStateChoices,
        default=AssetMonitoringStateChoices.DISABLED,
        help_text="Monitoring state of this LogicalInterface",
    )
    parent_interface = models.ForeignKey(
        to="DeviceInterface", related_name="%(class)s", on_delete=models.CASCADE
    )
    mtu = models.PositiveIntegerField(blank=True, null=True)
    type = models.CharField(
        choices=LOGICAL_INTERFACE_TYPE_CHOICES,
        max_length=2,
        default=None,
    )
    vrf = models.ForeignKey(
        to="VRF", related_name="%(class)s_vrf", on_delete=models.CASCADE, blank=True, null=True
    )
    ipv4_address = models.ForeignKey(
        to="ipam.IPAddress",
        related_name="%(class)s_ipv4_address",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    ipv6_address = models.ForeignKey(
        to="ipam.IPAddress",
        related_name="%(class)s_ipv6_address",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    mode = models.CharField(
        choices=LOGICAL_INTERFACE_MODE_CHOICES,
        blank=True,
        null=True,
        default=None,
        max_length=20,
        help_text="Interface mode (802.1Q)",
    )
    untagged_vlan = models.ForeignKey(
        to="VLAN",
        related_name="%(class)s_untagged_vlan",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
    )
    tagged_vlans = models.ManyToManyField(
        to="VLAN", related_name="%(class)s_tagged_vlans", blank=True, default=None
    )
    native_vlan = models.ForeignKey(
        to="VLAN",
        related_name="%(class)s_native_vlan",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
    )
    description = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.parent_interface.name}--{self.index}"

    def clean(self):
        # List of checks to perform
        if self.untagged_vlan and (self.tagged_vlans.exists() or self.native_vlan):
            raise ValidationError(
                "Untagged VLAN cannot be combined with tagged VLANs or native VLAN."
            )

        super(LogicalInterface, self).clean()

    def save(self, *args, **kwargs):
        self.full_clean()
        super(LogicalInterface, self).save(*args, **kwargs)

    class Meta:
        unique_together = ("index", "parent_interface")


class Link(ChangeLoggedModel):
    """A link between two DeviceInterface."""

    interface_a = models.ForeignKey(
        to="DeviceInterface",
        related_name="%(class)s_interface_a",
        on_delete=models.CASCADE,
    )
    interface_b = models.ForeignKey(
        to="DeviceInterface",
        related_name="%(class)s_interface_b",
        on_delete=models.CASCADE,
    )
    state = models.CharField(
        max_length=50,
        choices=AssetStateChoices,
        default=AssetStateChoices.STATE_STAGING,
        help_text="State of this Link",
    )
    monitoring_state = models.CharField(
        max_length=50,
        choices=AssetMonitoringStateChoices,
        default=AssetMonitoringStateChoices.DISABLED,
        help_text="Monitoring state of this Link",
    )

    def __str__(self):
        return f"{self.interface_a} <--> {self.interface_b}"


class PortLayout(ChangeLoggedModel):
    """A port layout configuration on a Network device."""

    device_type = models.ForeignKey(
        to="dcim.DeviceType",
        related_name="%(class)s_device_type",
        on_delete=models.CASCADE,
        help_text="The hardware associated with this PortLayout",
    )
    network_role = models.ForeignKey(
        to="dcim.DeviceRole",
        related_name="%(class)s_network_role",
        on_delete=models.CASCADE,
        help_text="The specific network role this port layout is designed to support.",
    )
    name = models.CharField(max_length=64, help_text="The generic name assigned to the interface.")
    label_name = models.CharField(
        max_length=64, help_text="The physical label name of the interface on the device."
    )
    logical_name = models.CharField(
        max_length=64, help_text="The logical name used to identify the interface in the system."
    )
    vendor_name = models.CharField(
        max_length=64, help_text="The vendor-specific name of the interface."
    )
    vendor_short_name = models.CharField(
        max_length=64, help_text="The short vendor-specific name of the interface."
    )
    vendor_long_name = models.CharField(
        max_length=64, help_text="The long vendor-specific name of the interface."
    )

netbox_cmdb/netbox_cmdb/api/route_policy/views.py
"""Route Policy views."""

from netbox_cmdb.api.route_policy.serializers import WritableRoutePolicySerializer
from netbox_cmdb.api.viewsets import CustomNetBoxModelViewSet
from netbox_cmdb.filtersets import RoutePolicyFilterSet
from netbox_cmdb.models.route_policy import RoutePolicy


class RoutePolicyViewSet(CustomNetBoxModelViewSet):
    queryset = RoutePolicy.objects.all()
    serializer_class = WritableRoutePolicySerializer
    filterset_class = RoutePolicyFilterSet

netbox_cmdb/netbox_cmdb/templates/netbox_cmdb/asn.html
{% extends 'generic/object.html' %}

{% block content %}
<div class="row">
  <div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">
                ASN
            </h5>
            <div class="card-body">
                <table class="table table-hover attr-table">
                    <tr>
                        <td>Number</td>
                        <td>{{ object.number }}</td>
                    </tr>
                    <tr>
                      <td>Organization name</td>
                      <td>{{ object.organization_name }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

netbox_cmdb/netbox_cmdb/templates/netbox_cmdb/asn_list.html
{% extends 'generic/object_list.html' %}

netbox_cmdb/netbox_cmdb/templates/netbox_cmdb/bgppeergroup.html
{% extends 'generic/object.html' %}

{% block content %}
<div class="row">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">Peer Group</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <td>Name</td>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <td>Device</td>
            <td>{{ object.device }}</td>
          </tr>
          <tr>
            <td>Local ASN</td>
            <td>{{ object.local_asn }}</td>
          </tr>
          <tr>
            <td>Remote ASN</td>
            <td>{{ object.remote_asn }}</td>
          </tr>
          <tr>
            <td>Route-policy in</td>
            <td>{{ object.route_policy_in }}</td>
          </tr>
          <tr>
            <td>Route-policy out</td>
            <td>{{ object.route_policy_out }}</td>
          </tr>
          <tr>
            <td>Maximum prefixes</td>
            <td>{{ object.maximum_prefixes }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

netbox_cmdb/netbox_cmdb/templates/netbox_cmdb/bgppeergroup_list.html
{% extends 'generic/object_list.html' %}

netbox_cmdb/netbox_cmdb/templates/netbox_cmdb/bgpsession.html
{% extends 'generic/object.html' %} {% load helpers %}
{% block title %}{{ object.peer_a.device }} <> {{ object.peer_b.device }}{% endblock %}
{% block content %}
<div class="row">
  <div class="col col-12 col-xl-5">
    <div class="card">
      <h5 class="card-header">Peer A</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th>Device</th>
            <td>{{ object.peer_a.device|linkify}}</td>
          </tr>
          <tr>
            <th>Description</th>
            <td>{{ object.peer_a.description }}</td>
          </tr>
          <tr>
            <th>Local address</th>
            <td>{{ object.peer_a.local_address|linkify}}</td>
          </tr>
          <tr>
            <th>Local ASN</th>
            <td>{{ object.peer_a.local_asn|linkify}}</td>
          </tr>
          <tr>
            <th>Route Policy in</th>
            <td>{{ object.peer_a.route_policy_in|placeholder}}</td>
          </tr>
          <tr>
            <th>Route Policy out</th>
            <td>{{ object.peer_a.route_policy_out|placeholder}}</td>
          </tr>
          <tr>
            <th>Maximum prefixes</th>
            <td>{{ object.peer_a.maximum_prefixes }}</td>
          </tr>
          <tr>
            <th>Delay Open Timer</th>
            <td>{{ object.peer_a.delay_open_timer }}</td>
          </tr>
          <tr>
            <th>Enforce First AS</th>
            <td>{% checkmark object.peer_a.enforce_first_as %}</td>
          </tr>
          <tr>
            <th>Enabled</th>
            <td>{% checkmark object.peer_a.enabled %}</td>
          </tr>
        </table>
        <h5 class="card-text">AFI/SAFI</h5>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Route Policy in</th>
              <th scope="col">Route Policy out</th>
            </tr>
          </thead>
          <tbody>
            {% for afisafi in object.peer_b.afi_safis.all %}
            <tr>
              <td>{{ afisafi.afi_safi_name }}</td>
              <td>{{ afisafi.route_policy_in.name|placeholder}}</td>
              <td>{{ afisafi.route_policy_out.name|placeholder }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col col-12 col-xl-2">
    <div class="card">
      <h5 class="card-header">BGP Session</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th>State</th>
            <td>{% badge object.get_state_display bg_color=object.get_state_color%}</td>
          </tr>
          <tr>
            <th>Monitoring State</th>
            <td>{% badge object.get_monitoring_state_display bg_color=object.get_monitoring_state_color%}</td>
          </tr>
          <tr>
            <th>Password</th>
            <td>{{ object.password|placeholder }}</td>
          </tr>
          <tr>
            <th>Circuit</th>
            <td>{{ object.circuit|placeholder }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="col col-12 col-xl-5">
    <div class="card">
      <h5 class="card-header">Peer B</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th>Device</th>
            <td>{{ object.peer_b.device|linkify}}</td>
          </tr>
          <tr>
            <th>Description</th>
            <td>{{ object.peer_b.description }}</td>
          </tr>
          <tr>
            <th>Local address</th>
            <td>{{ object.peer_b.local_address|linkify}}</td>
          </tr>
          <tr>
            <th>Local ASN</th>
            <td>{{ object.peer_b.local_asn|linkify}}</td>
          </tr>
          <tr>
            <th>Route Policy in</th>
            <td>{{ object.peer_b.route_policy_in|placeholder}}</td>
          </tr>
          <tr>
            <th>Route Policy out</th>
            <td>{{ object.peer_b.route_policy_out|placeholder}}</td>
          </tr>
          <tr>
            <th>Maximum prefixes</th>
            <td>{{ object.peer_b.maximum_prefixes }}</td>
          </tr>
          <tr>
            <th>Delay Open Timer</th>
            <td>{{ object.peer_b.delay_open_timer }}</td>
          </tr>
          <tr>
            <th>Enforce First AS</th>
            <td>{% checkmark object.peer_b.enforce_first_as %}</td>
          </tr>
          <tr>
            <th>Enabled</th>
            <td>{% checkmark object.peer_b.enabled %}</td>
          </tr>
        </table>
        <h5 class="card-text">AFI/SAFI</h5>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Route Policy in</th>
              <th scope="col">Route Policy out</th>
            </tr>
          </thead>
          <tbody>
            {% for afisafi in object.peer_b.afi_safis.all %}
            <tr>
              <td>{{ afisafi.afi_safi_name }}</td>
              <td>{{ afisafi.route_policy_in.name}}</td>
              <td>{{ afisafi.route_policy_out.name }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col col-12 col-xl-5">
  {% if object.peer_a.peer_group %}
    <div class="card">
      <h5 class="card-header">Peer-Group A</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th>PG Name</td>
            <td>{{ object.peer_a.peer_group | linkify:"name" }}</td>
          </tr>
          <tr>
            <th>Description</td>
            <td>{{ object.peer_a.peer_group.description }}</td>
          </tr>
          <tr>
            <th>Local address</td>
            <td>{{ object.peer_a.peer_group.local_address|placeholder|linkify}}</td>
          </tr>
          <tr>
            <th>Local ASN</td>
            <td>{{ object.peer_a.peer_group.local_asn|placeholder|linkify}}</td>
          </tr>
          <tr>
            <th>Route Policy in</td>
            <td>{{ object.peer_a.peer_group.route_policy_in|placeholder|linkify:"name"}}</td>
          </tr>
          <tr>
            <th>Route Policy out</td>
            <td>{{ object.peer_a.peer_group.route_policy_out|placeholder|linkify:"name"}}</td>
          </tr>
          <tr>
            <th>Maximum prefixes</td>
            <td>{{ object.peer_a.peer_group.maximum_prefixes|placeholder }}</td>
          </tr>
        </table>
      </div>
    </div>
  {% endif %}
  </div>
  <div class="col col-12 col-xl-2">
  </div>
  <div class="col col-12 col-xl-5">
    {% if object.peer_b.peer_group %}
    <div class="card">
      <h5 class="card-header">Peer-Group B</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th>PG Name</td>
            <td>{{ object.peer_b.peer_group  | linkify:"name" }}</td>
          </tr>
          <tr>
            <th>Description</td>
            <td>{{ object.peer_b.peer_group.description }}</td>
          </tr>
          <tr>
            <th>Local address</td>
            <td>{{ object.peer_b.peer_group.local_address|placeholder|linkify}}</td>
          </tr>
          <tr>
            <th>Local ASN</td>
            <td>{{ object.peer_b.peer_group.local_asn|placeholder|linkify}}</td>
          </tr>
          <tr>
            <th>Route Policy in</td>
            <td>{{ object.peer_b.peer_group.route_policy_in|placeholder|linkify:"name"}}</td>
          </tr>
          <tr>
            <th>Route Policy out</td>
            <td>{{ object.peer_b.peer_group.route_policy_out|placeholder|linkify:"name"}}</td>
          </tr>
          <tr>
            <th>Maximum prefixes</td>
            <td>{{ object.peer_b.peer_group.maximum_prefixes|placeholder }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% endif %}
  </div>
{% endblock %}

netbox_cmdb/netbox_cmdb/templates/netbox_cmdb/bgpsession_list.html
{% extends 'generic/object_list.html' %}